"""add search_strategy_outcomes table

Revision ID: 6be679fdf5be
Revises: p6q7r8s9t0u1
Create Date: 2026-06-17 01:43:46.896933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '6be679fdf5be'
down_revision: Union[str, None] = 'p6q7r8s9t0u1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_strategy_outcomes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scan_id', sa.UUID(), nullable=False),
    sa.Column('confirmed_release_id', sa.Integer(), nullable=False),
    sa.Column('strategy_name', sa.String(length=50), nullable=False),
    sa.Column('hit', sa.Boolean(), nullable=False),
    sa.Column('was_first', sa.Boolean(), nullable=False),
    sa.Column('rank_in_strategy', sa.Integer(), nullable=True),
    sa.Column('error', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_strategy_outcomes_scan_id'), 'search_strategy_outcomes', ['scan_id'], unique=False)
    op.create_index(op.f('ix_search_strategy_outcomes_strategy_name'), 'search_strategy_outcomes', ['strategy_name'], unique=False)
    op.create_index('ix_strategy_outcomes_strategy_hit', 'search_strategy_outcomes', ['strategy_name', 'hit'], unique=False)
    op.drop_index('ix_invites_token', table_name='invites')
    op.drop_index('ix_prt_token', table_name='password_reset_tokens')
    op.drop_index('ix_records_discogs_instance_id', table_name='records')
    op.drop_index('ix_records_genre', table_name='records')
    op.drop_index('ix_users_email', table_name='users', postgresql_where='(email IS NOT NULL)')
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index('ix_users_email', 'users', ['email'], unique=True, postgresql_where='(email IS NOT NULL)')
    op.create_index('ix_records_genre', 'records', ['user_id', 'genre'], unique=False)
    op.create_index('ix_records_discogs_instance_id', 'records', ['discogs_instance_id'], unique=False)
    op.create_index('ix_prt_token', 'password_reset_tokens', ['token'], unique=True)
    op.create_index('ix_invites_token', 'invites', ['token'], unique=True)
    op.drop_index('ix_strategy_outcomes_strategy_hit', table_name='search_strategy_outcomes')
    op.drop_index(op.f('ix_search_strategy_outcomes_strategy_name'), table_name='search_strategy_outcomes')
    op.drop_index(op.f('ix_search_strategy_outcomes_scan_id'), table_name='search_strategy_outcomes')
    op.drop_table('search_strategy_outcomes')
    # ### end Alembic commands ###
